#!/bin/bash

# by xjlsigmaboy <github.com/xjlsigmaboy>

# Variables
username=$USER
hostname=$(uname -n)
arch=$(uname -m)
os_name=$(cat /etc/*-release | grep "PRETTY_NAME" | sed 's/PRETTY_NAME=//g' | sed 's/"//g')
kernel=$(uname -r)
shell=$SHELL
uptime=$(uptime -p)
desktop=$XDG_SESSION_DESKTOP
cpu_name=$(lscpu | grep -i "Model name" | cut -d ':' -f 2 | sed 's/^\s*//g')
gpu_name=$(lspci | grep -i "VGA" | cut -d ':' -f 3 | sed 's/^\s*//g')
distro=$(cat /etc/os-release | grep PRETTY_NAME | cut -d '=' -f 2 | sed 's/\"//g')
ram=$(free -h | awk '/^Mem/ { print $3"\\"$2 }' | sed s/i//g)
# Determine the appropriate command based on the distribution
case "$distro" in
    "Debian GNU/Linux 12 (bookworm)"|Ubuntu)
        cmd="dpkg -l | grep '^ii' | wc -l"
        ;;
    Fedora|CentOS|RHEL)
        cmd="rpm -qa | wc -l"
        ;;
    "Arch Linux"|EndeavourOS)
        cmd="pacman -Q | wc -l"
        ;;
    Gentoo)
        cmd="qlist -I | wc -l"
        ;;
    NixOS)
        cmd="nix-env -qa | wc -l"
        ;;
    "Void Linux")
	cmd="xbps-query --list-pkgs | wc -l"
	;;
    "Alpine Linux edge")
    	cmd="apk list -I | wc -l"
	;;
	*)
        echo "Unsupported distribution: $distro"
        exit 1
        ;;
esac

package_count=$(eval "$cmd")

# colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magneta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
reset=$(tput sgr0)

# info
echo ""
echo "$red $USER$reset@$green$hostname$reset"
echo "$green--------------------------------------$reset"
printf "$yellow OS$reset: $os_name\n"
printf "$yellow kernel$reset: $kernel\n"
printf "$yellow Arch$reset: $arch\n"
printf "$yellow Uptime$reset: $uptime\n"
printf "$yellow Shell$reset: $shell\n"
printf "$yellow PKGS$reset: $package_count\n"
printf "$yellow DE/WM$reset: $desktop\n"
echo "$yellow RAM$reset: $ram"
printf "$yellow CPU$reset: $cpu_name\n"
printf "$yellow GPU$reset: $gpu_name\n"
echo "$green--------------------------------------$reset"
echo ""
